esphome:
  name: proximity-sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "bcsVNZwPws2KcWW4RViw5zj7vFWIr8sBLHSdC3cCXWw="

ota:
  password: "532cd30eddd4686a9c1cb5909de3bfb5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Proximity-Sensor"
    password: "mkVoz06pNqRB"

captive_portal:

globals:
 # Set this to the distance detected by the ultrasonic sensor. Default is 2m.
 - id: maximum_distance
   type: float
   initial_value: '0.7'
 # How many distance readings to detect before reporting value (smooth false positives)
 - id: reporting_interval
   type: int
   initial_value: '2'
 # Do not change the following globals
 - id: detected_readings
   type: int
   restore_value: no
   initial_value: '0'
 - id: previous_reading_nan
   type: boolean
   restore_value: no
   initial_value: 'true'
 - id: previous_reading
   type: float
   restore_value: no
   initial_value: '20.0'

 # Do not change the following globals
 - id: detected_readings_1
   type: int
   restore_value: no
   initial_value: '0'
 - id: previous_reading_nan_1
   type: boolean
   restore_value: no
   initial_value: 'true'
 - id: previous_reading_1
   type: float
   restore_value: no
   initial_value: '20.0'

sensor:
  # This is the physical sensor, not published to Home Assistant
  - platform: ultrasonic
    trigger_pin: GPIO3
    echo_pin: GPIO19
    name: "Ultrasonic Distance Raw"
    update_interval: 1s
    id: ultrasonic_distance_raw
    internal: true

  - platform: ultrasonic
    trigger_pin: GPIO18
    echo_pin: GPIO16
    name: "Ultrasonic Distance Raw 1"
    update_interval: 1s
    id: ultrasonic_distance_raw_1
    internal: true

  # This is a virtual sensor to smooth the false positive readings
  - platform: template
    id: ultrasonic_distance
    name: "Ultrasonic Distance"
    update_interval: 1s
    lambda: |-
      ESP_LOGD("Ultrasonic", "Got %d readings in a row", id(detected_readings));
      if (id(ultrasonic_distance_raw).state < id(maximum_distance)) {
        // We have a reading... don't use it, just remember that we got one, but not if we're already at the limit of how many we need
        ESP_LOGD("Ultrasonic", "We have a reading... don't use it, just remember that we got one.");
        if(id(previous_reading_nan) == true) {
          id(previous_reading_nan) = false;
          id(detected_readings) = 0;
        }
        if( id(detected_readings) < id(reporting_interval) ) {
          id(detected_readings) += 1;
        }
      }
      else {
        // We got a NAN reading (out of range). Reset the readings counter
        if(id(previous_reading_nan) == false) {
          id(previous_reading_nan) = true;
          id(detected_readings) = 0;
        }
        if( id(detected_readings) < id(reporting_interval) ) {
          id(detected_readings) += 1;
        }
        ESP_LOGD("Ultrasonic", "We got a NAN reading (out of range). Reset the readings counter");
        id(previous_reading_nan) = true;
      }
      
      if( id(detected_readings) >= id(reporting_interval)) {
        // We have gathered enough readings in a row to report
        if(id(previous_reading_nan) == false) {
          id(previous_reading) = id(ultrasonic_distance_raw).state;
          return id(ultrasonic_distance_raw).state;
        }
        else {
          ESP_LOGD("Ultrasonic", "We have gathered enough readings in a row to report: %f", id(maximum_distance));
          id(previous_reading) = id(maximum_distance);
          return id(maximum_distance); 
        }
      }
      return id(previous_reading);

    # This is a virtual sensor to smooth the false positive readings
  - platform: template
    id: ultrasonic_distance_1
    name: "Ultrasonic Distance 1"
    update_interval: 1s
    lambda: |-
      ESP_LOGD("Ultrasonic", "Got %d readings in a row", id(detected_readings_1));
      if (id(ultrasonic_distance_raw_1).state < id(maximum_distance)) {
        // We have a reading... don't use it, just remember that we got one, but not if we're already at the limit of how many we need
        ESP_LOGD("Ultrasonic", "We have a reading... don't use it, just remember that we got one.");
        if(id(previous_reading_nan_1) == true) {
          id(previous_reading_nan_1) = false;
          id(detected_readings_1) = 0;
        }
        if( id(detected_readings_1) < id(reporting_interval) ) {
          id(detected_readings_1) += 1;
        }
      }
      else {
        // We got a NAN reading (out of range). Reset the readings counter
        if(id(previous_reading_nan_1) == false) {
          id(previous_reading_nan_1) = true;
          id(detected_readings_1) = 0;
        }
        if( id(detected_readings_1) < id(reporting_interval) ) {
          id(detected_readings_1) += 1;
        }
        ESP_LOGD("Ultrasonic", "We got a NAN reading (out of range). Reset the readings counter");
        id(previous_reading_nan_1) = true;
      }
     
      if( id(detected_readings_1) >= id(reporting_interval)) {
        // We have gathered enough readings in a row to report
        if(id(previous_reading_nan_1) == false) {
         id(previous_reading_1) = id(ultrasonic_distance_raw_1).state;
          return id(ultrasonic_distance_raw_1).state;
        }
        else {
          ESP_LOGD("Ultrasonic", "We have gathered enough readings in a row to report: %f", id(maximum_distance));
          id(previous_reading_1) = id(maximum_distance);
          return id(maximum_distance); 
        }
      }
      return id(previous_reading_1);
binary_sensor:
  - platform: template
    name: "Ultrasonic Presence"
    lambda: |-
      if (id(ultrasonic_distance).state < id(maximum_distance)) {
        // Presence is detected
        return true;
      } else {
        // No presence detected.
        return false;
      }
    filters:
      - delayed_off: 5000ms

  - platform: template
    name: "Ultrasonic Presence 1"
    lambda: |-
      if (id(ultrasonic_distance_1).state < id(maximum_distance)) {
        // Presence is detected
        return true;
      } else {
        // No presence detected.
        return false;
      }
    filters:
      - delayed_off: 5000ms

  - platform: template
    name: "Desk Presence"
    icon: mdi:desk
    device_class: presence
    lambda: !lambda |-
      if ((id(ultrasonic_distance).state < id(maximum_distance)) or (id(ultrasonic_distance_1).state < id(maximum_distance))) {
        return true;
      } else {
        return false;
      }
